### ISSUE TITLE
Generate fly through surface reconstructions

### ISSUE THREAD

**Issue by shreyasaha1997** [lppllppl920/SAGE-SLAM#10]
I do see in the github repo that fly-through surface reconstruction results are present, and I am trying to generate the same. I understand that the script - 'generate_reconstruction_fly_through.py' should be used, but it requires a lot of input files that I am not entirely sure how to generate. It would be very useful if you can show an example of how to use the script.

**Comment by lppllppl920** [comment]
You should be able to find those input files if you run SLAM and produce output data.
