### ISSUE TITLE
Step 9: There is no build file after running

### ISSUE THREAD

**Issue by ultimateGao** [lppllppl920/SAGE-SLAM#11]
Hello dear author
When I ran to step 9 according to the steps you provided (of which steps 6, 7, and 8 I skipped directly without running), the error **"Building TEASER-plusplus"
make: *** No rule to make target 'install'.  Stop."**,
and after using tree -d -L 3, the build folder did not appear in the project file directory , and where the command for step nine I was running in the docker desktop terminal

**Comment by lppllppl920** [comment]
Step 9 provides a command to create the build folder. It is possible that you didn't run those commands successfully.

**Comment by ultimateGao** [comment]
Thanks to the author, after I re-ran it, there are no problems anymore
