### ISSUE TITLE
TypeError: can't pickle cv2.FastFeatureDetector objects

### ISSUE THREAD

**Issue by Tokymin** [lppllppl920/SAGE-SLAM#2]
I encountered this error in the 280 line of trainning.py 

`for curr_iter, input_dict in enumerate(train_loader):`

![图片](https://user-images.githubusercontent.com/32712253/158924719-10a27299-d6ee-4c7e-bfcb-8dbf2f38b50b.png)
I'm not sure if it is caused by the OpenCV version.

**Comment by lppllppl920** [comment]
Hi Tokymin,

Did you try to run the script inside the docker container? The environment is already set up in the Dockerfile.
