### ISSUE TITLE
ValueError: a must be non-empty?

### ISSUE THREAD

**Issue by LINFF1023** [lppllppl920/SAGE-SLAM#6]
There was an error running step 6.
why?
Looking forward to the author's reply!!!

**Comment by lppllppl920** [comment]
Could you provide more details on this issue?

**Comment by LINFF1023** [comment]
> Could you provide more details on this issue?

![Uploading 111.png…]()
when i python3 training.py --config_path "configs/training.json"  ,this happened.

**Comment by LINFF1023** [comment]
> Could you provide more details on this issue?

![111](https://user-images.githubusercontent.com/108864853/189816699-67ba095c-6da9-4f85-a109-923353e9390d.png)
when i python3 training.py --config_path "configs/training.json", this happened.

**Comment by lppllppl920** [comment]
This means the dataset class couldn’t find hdf5 data. Please make sure you download hdf5 data to the correct path 

`self.sequence_hdf5_path_list = sorted(
            list(self.data_root.rglob(hdf5_pattern)) `

**Comment by LINFF1023** [comment]
> This means the dataset class couldn’t find hdf5 data. Please make sure you download hdf5 data to the correct path
> 
> `self.sequence_hdf5_path_list = sorted( list(self.data_root.rglob(hdf5_pattern)) `

i think so too...thanks ！！

**Comment by LINFF1023** [comment]
> Could you provide more details on this issue?

![222](https://user-images.githubusercontent.com/108864853/190070511-1d9fe529-c0f8-4351-ba0e-72da9c342f93.png)
I'm sorry to bother you again.I'm a newbie but I really want to run your code successfully.I really don't understand this problem but my classmate said it might be the version problem(torch).

**Comment by lppllppl920** [comment]
Could you try updating the Dockerfile with the latest one and try the instructions again? It could be that the PyTorch version issue. I didn’t test thoroughly before updating the PyTorch base image a couple of days ago.
