### ISSUE TITLE
std_depth && render_depth

### ISSUE THREAD

**Issue by DavidLuBit** [lppllppl920/SAGE-SLAM#7]
Hello~Sorry to bother you~I want to know the difference between std_depth and render_depth in the given datasets, besides, how can I acquire them?
Thank you~

**Comment by lppllppl920** [comment]
Hi,

std_depth is the predicted depth uncertainty from a depth network and render_depth is the depth rendering of the 3d surface reconstruction. Both of those can be generated with [this method](https://github.com/lppllppl920/DenseReconstruction-Pytorch)

**Comment by DavidLuBit** [comment]
OK~I got it! Thanks a lot!!
