### ISSUE TITLE
BOW model

### ISSUE THREAD

**Issue by DavidLuBit** [lppllppl920/SAGE-SLAM#8]
Hi auther~I wonder if I need to train the Bag-Of-Word model on my datasets ?

**Comment by lppllppl920** [comment]
Hi,

The provided BoW model was trained on the nasal endoscopy dataset we had. It is likely the model will still work fine in your scenario if you did not re-train the feature network and the textures of your testing scenario look similar. You can tell whether or not BoW model performs well by enabling the debugging mode and see if the global loop closure can be successfully detected.

**Comment by DavidLuBit** [comment]
Thanks a lot~!!! I have to retrain the feature network on my gastroscope datasets,  I'd like to know what is the input of BoW model, the original endoscopy image or the feature map? Thanks a lot for your detailed answer!!!!

**Comment by lppllppl920** [comment]
It is the feature map. You can find the code to generate a new BoW dictionary in this repo.

**Comment by DavidLuBit** [comment]
OK ~ Thanks a lot~!
