### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by Taogonglin** [lppllppl920/SAGE-SLAM#9]
hello, the data bag_1 is the full dataset? if not, could you give me the whole dataset? there are only about 1000 pictures, I want to get all to train other model thank you?

**Comment by lppllppl920** [comment]
The dataset is internal and not available publicly

**Comment by Taogonglin** [comment]
> 

ok, thank you

**Comment by Taogonglin** [comment]
> The dataset is internal and not available publicly

hello, I truly want this dataset, I don;t find other dataset to replace this dataset, I'm a China student, I can give you my information if you can give me this dataset. Sorry for aboving you

**Comment by lppllppl920** [comment]
> > The dataset is internal and not available publicly
> 
> hello, I truly want this dataset, I don;t find other dataset to replace this dataset, I'm a China student, I can give you my information if you can give me this dataset. Sorry for aboving you

You can try to contact the communication author of this paper, Dr. Mathias Unberath, to see if he can approve this request. Unfortunately, I have graduated and therefore do not have the permission of sharing the data with you.

**Comment by Taogonglin** [comment]
> > > The dataset is internal and not available publicly
> > 
> > 
> > hello, I truly want this dataset, I don;t find other dataset to replace this dataset, I'm a China student, I can give you my information if you can give me this dataset. Sorry for aboving you
> 
> You can try to contact the communication author of this paper, Dr. Mathias Unberath, to see if he can approve this request. Unfortunately, I have graduated and therefore do not have the permission of sharing the data with you.

thank you, but how can I contact the author?

**Comment by lppllppl920** [comment]
You can find the contact information in the README of this repo.
